#
# Module manifest for module 'CorpApps'
#
# Generated by: Michael.West
#
# Generated on: 12/6/2012
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = '.\CorpApps.psm1'

    # Version number of this module.
    ModuleVersion = '1.0'

    # ID used to uniquely identify this module
    GUID = '7733255f-f2eb-4973-8c8a-4e9199944627'

    # Author of this module
    Author = 'Michael.West'

    # Company or vendor of this module
    CompanyName = 'Popular Company Name, Inc.'

    # Copyright statement for this module
    Copyright = '(c) 2013 Michael.West. All rights reserved.'

    # Description of the functionality provided by this module
    # Description = ''

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = '3.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of the .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @('.\types.ps1xml')

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
        '.\Compress-Alias.ps1',
        '.\Compress-Archive.ps1',
        '.\ConvertFrom-Base64.ps1',
        '.\ConvertTo-Base64.ps1',
        '.\ConvertTo-HashTable.ps1',
        '.\ConvertTo-PlainText.ps1',
        '.\Expand-Archive.ps1',
        '.\Export-Xlsx.ps1',
        '.\Get-FirewallRules.ps1',
        '.\Get-LocalGroupUser.ps1',
        '.\Get-LocalUser.ps1',
        '.\Get-Function.ps1',
        '.\Get-MachineAppSetting.ps1',
        '.\Get-ParameterOption.ps1',
        '.\Get-RemoteDesktop.ps1',
        '.\Get-ScriptDirectory.ps1',
        '.\Import-Xlsx.ps1',
        '.\Invoke-Ternary.ps1',
        '.\Invoke-SqlCommand.ps1',
        '.\Invoke-Ternary.ps1',
        '.\Join-Object.ps1'
        '.\Measure-StringDistance.ps1',
        '.\New-LocalUser.ps1',
        '.\Out-StringEx.ps1',
        '.\Remove-LocalUser.ps1',
        '.\Send-File.ps1',
        '.\Set-LocalUser.ps1',
        '.\Set-MachineAppSetting.ps1',
        '.\Set-RemoteDesktop.ps1',
        '.\Split-UserName.ps1',
        '.\Start-Transcript.ps1',
        '.\Stop-Transcript.ps1',
        '.\Test-Command.ps1',
        '.\Test-Credential.ps1',
        '.\Test-Email.ps1',
        '.\Test-PSRemoting.ps1',
        '.\Test-TcpPort.ps1',
        '.\Write-Log.ps1'
    )
    
    # Functions to export from this module
    FunctionsToExport = @(
        'Compress-Alias',
        'Compress-Archive',
        'ConvertFrom-Base64',
        'ConvertTo-Base64',
        'ConvertTo-HashTable',
        'ConvertTo-PlainText',
        'Expand-Archive',
        'Export-Xlsx',
        'Get-ActiveDirectoryAccount',
        'Get-FirewallRules',
        'Get-Function',
        'Get-LocalGroupUser',
        'Get-LocalUser',
        'Get-MachineAppSetting',
        'Get-ParameterOption',
        'Get-RemoteDesktop',
        'Get-ScriptDirectory',
        'Import-Xlsx',
        'Invoke-SqlCommand',
        'Join-Object',
        'Measure-StringDistance',
        'New-LocalUser',
        'Remove-LocalUser',
        'Send-File',
        'Set-LocalUser',
        'Set-MachineAppSetting',
        'Set-RemoteDesktop',
        'Split-UserName',
        'Start-Transcript',
        'Stop-Transcript',
        'Test-Command',
        'Test-Credential',
        'Test-Email',
        'Test-PSRemoting',
        'Test-TcpPort',
        'Write-Log'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @('?:')

    # List of all modules packaged with this module.
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    # PrivateData = ''

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = 'CA'
}
